// <auto-generated />
namespace BSU.FAMCS.LoadMonitoring.DataBaseLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class VolumeNameAdding : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(VolumeNameAdding));
        
        string IMigrationMetadata.Id
        {
            get { return "201505282135556_VolumeNameAdding"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
